### ISSUE TITLE
[meta] add logging to codebase

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#110]
Commands in need of logging
- [x] init
- [X] build @fredkschott
- [X] Help
- [x] Lint @fredkschott (needed inside of polylint)
- [x] Serve @fredkschott (needed inside of polyserve)
- [x] Test @fredkschott (needed inside of WCT)

**Comment by FredKSchott** [comment]
@justinfagnani @azakus @garlicnation if any of you guys are doing enough work to any of these commands that I shouldn't touch them, let me know asap.

**Comment by justinfagnani** [comment]
Seems fixed enough for now. We need to visit all of our libraries soon.

**Comment by FredKSchott** [comment]
Haha you just beat me to it. Just filed the last PR in WCT
