### ISSUE TITLE
v0.18.0 Dependency Tracker

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#499]
### `polymer init`
- [X] no dependencies

### `polymer install`
- [X] no dependencies

### `polymer lint`
- [X] currently on stable release

### `polymer build`
- [x] needs polymer-analyzer caching (@rictic)
- [x] needs to stamp v0.6.0
- [x] v0.6.0 needs to be updated in polymer-cli

### `polymer serve`
- [ ] needs to stamp v0.16.0
- [ ] v0.16.0 needs to be updated in polymer-cli

### `polymer test`
- ?
- [ ] wct needs to stamp v6.0.0
- [ ] v6.0.0 needs to be updated in polymer-cli

**Comment by abdonrd** [comment]
ETA? :)

**Comment by FredKSchott** [comment]
Moving to milestone tracking
