### ISSUE TITLE
Polymer 2.0 Build Permutations and Improvements

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#507]
- [x] Create single build instead of `bundle` & `unbundle` builds as default #509 
- [x] `--bundle` build flag #509 
- [x] rename `--insert-dependency-links` to `--insert-prefetch-links` #510
- [x] `--js-compile` build flag #525 
- [x] replace uglify with babili #525  
- [x] `--add-service-worker` build flag #534
- [x] reintroduce multiple builds via polymer.json named builds #545 
- [x] decide what default build case should be. All off? (Design Doc)
- [x] make sure we have a good migration story. Which options to continue to support? (Design Doc)
- [X] Cleanup changelog #551 
- [ ] add helpful message to "UNKNOWN_OPTION" error (optional, if there are issues with the `next` release)
- [ ] Add stronger build unit & integration tests (to do later)
- [ ] ~~`--polyfill=['none'|'partial'|'full']` build flag~~

**Comment by yordis** [comment]
@FredKSchott will this allow me to add `.babelrc` in my project and it will use it? So I can add `babel-preset-env` if I want.

Also, could you add `autoprefixer` and allow me to add the `browserlist` in my project so I can configure the output?

**Comment by yordis** [comment]
Btw, it will be great if I can define either `babelrc` or `browserlist` in the command line so we can support multiple builds. Example: `polymer build --babelrc="path/here" --browserlist="path/here"`

For example, one of my case I have to support IE11, but I don't want to ship the same version of the Javascript file for the modern browsers. They have almost 100% of ES6 support, so the trade off is big 😢

**Comment by FredKSchott** [comment]
@yordis supporting multiple builds is the plan (see list above).

Once this is done we can look into supporting the ability to pass in your own .babelrc file. We really want to support that, but it's a bit of a foot-gun because the modules transform that is a part of `es2015` preset changes the global scope of the file.

**Comment by yordis** [comment]
@FredKSchott I didn't understand the concern about the module transform

**Comment by justinfagnani** [comment]
Modules and classic scripts have differences that cause problems when interpreting a script as module. The one I already hit in some testing libraries is that top-level `this` is undefined in modules. 

The compilation feature might make more sense when you view it as leveling the language features available supported browsers, not providing configurable language transforms like Babel in general. We want to be able to send uncompiled source to the latest browsers, so we can't support features that they don't.
